[package]
name = "ethers-signers"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

[dependencies]
ethers-types = { path = "../ethers-types" }
ethers-providers = { path = "../ethers-providers" }
ethers-utils = { path = "../ethers-utils" }
