[package]
name = "ethers"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

[dependencies]
solc = { git = "https://github.com/paritytech/rust_solc "}
ethereum-types = "0.9.2"
url = "2.1.1"
once_cell = "1.4.0"
async-trait = "0.1.31"
reqwest = { version = "0.10.4", features = ["json"] }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
thiserror = "1.0.19"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros"] }
