[package]
name = "ethers"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

[dependencies]
ethereum-types = { version = "0.9.2", default-features = false, features = ["serialize"] }
url = { version = "2.1.1", default-features = false }
async-trait = { version = "0.1.31", default-features = false }
reqwest = { version = "0.10.4", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.110", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.53", default-features = false }
thiserror = { version = "1.0.19", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
rand = { version = "0.5.1", default-features = false } # this should be the same rand crate version as the one in secp
secp256k1 = { version = "0.17.2", default-features = false, features = ["std", "recovery", "rand"] }
zeroize = { version = "1.1.0", default-features = false }
tiny-keccak = { version = "2.0.2", default-features = false }

solc = { git = "https://github.com/paritytech/rust_solc "}
rlp = "0.4.5"
ethabi = "12.0.0"
bincode = "1.2.1"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros"] }
failure = "0.1.8"
rand = { version = "0.5.1" }
