[package]
name = "ethers"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

[dependencies]
ethereum-types = { version = "0.9.2", default-features = false, features = ["serialize"] }
url = { version = "2.1.1", default-features = false }
async-trait = "0.1.31"
reqwest = { version = "0.10.4", default-features = false, features = ["json"] }
serde = { version = "1.0.110", default-features = false, features = ["derive"] }
serde_json = "1.0.53"
thiserror = "1.0.19"
rustc-hex = "2.1.0"
rand = "0.5.1" # this should be the same rand crate version as the one in secp
secp256k1 = { version = "0.17.2", features = ["recovery", "rand"] }
secrecy = "0.6.0"
zeroize = "1.1.0"
tiny-keccak = "2.0.2"
futures = "0.3.5"

solc = { git = "https://github.com/paritytech/rust_solc "}
rlp = "0.4.5"

[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros"] }
failure = "0.1.8"

