[workspace]

members = [
    "./crates/ethers",
    "./crates/ethers-abi",
    "./crates/ethers-contract",
    "./crates/ethers-providers",
    "./crates/ethers-signers",
    "./crates/ethers-types",
    "./crates/ethers-utils",
]
