[package]
name = "ethers-contract-derive"
version = "0.1.0"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>", "Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Proc macro for type-safe bindings generation to Ethereum smart contracts"

[lib]
proc-macro = true

[dependencies]
ethers-core = { path = "../../ethers-core" }
ethers-contract-abigen = { path = "../ethers-contract-abigen" }

serde_json = "1.0.53"

proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0.12"
