version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
              cargo install cargo-audit
              rustup component add clippy
      - run: cargo test --all
      - run:
          name: Check style
          command: |
              cargo fmt --all -- --check
              cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: Audit Dependencies
          command: cargo audit
